### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by shadow01148**

### CODE REVIEW

**Comment by shadow01148** [comment]
ill update the readme i promise
just merge my previous pr and this one

**Comment by NexitySecond** [comment]
mf stop doing main.js thats what im doing rn

**Comment by shadow01148** [comment]
> mf stop doing main.js thats what im doing rn

i didnt modify anything, im just adding things (it wont interfere)

**Comment by Volas171** [comment]
> mf stop doing main.js thats what im doing rn

mf have you heard about git pull

**Pull request closed without merging**
